version: "3.9"

services:
  server:
    # Build image from Dockerfile
    build: .
    restart: unless-stopped
    volumes:
      # Mount the current directory to the container
      - .:/app
    ports:
      # HTTP server
      - "3000:3000"
      # Athena WebSocket
      - "4040:4040"
  worker:
    # Use the same image as the server
    build: .
    # But run the worker.js script instead
    command: /usr/local/bin/node worker.js
    restart: unless-stopped
    volumes:
      - .:/app
#  # Optionally, start the retropilot-client (assuming it is in the parent directory)
#  client:
#    # Use retropilot-client image
#    build:
#      context: ../retropilot-client
#      dockerfile: ../retropilot-client/Dockerfile
#      args:
#        # Override .env.production in retropilot-client
#        PUBLIC_URL: http://localhost:8080
#        API_URL: http://localhost:3000
#    restart: unless-stopped
#    ports:
#      # Bind container port 80 to host port 8080
#      - "8080:80"
