version: "3.0"
services:
  server:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
      - "4040:4040"
  worker:
    build: .
    command: node -r esm src/worker
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: postgres:14-bullseye
    restart: always
    ports:
      - '5438:5432'
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
