version: "3.0"
services:
  server:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
      - "4040:4040"
  db:
    image: postgres
    restart: always
    ports:
      - '5438:5432'
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: retro-pilot
